#!/bin/bash

if [[ ! -f ./releaser ]];then
  wget http://http.archive.ai-traders.com/releaser/0.3.0/releaser || { echo "failed to wget releaser"; exit 1; }
fi
source ./releaser
docker_ops=$(readlink -f ../../../../src/docker-ops)
source ${docker_ops}
# This goes as last in order to let end user variables override default values
releaser_init

command="$1"
case "${command}" in
  build)
      docker_build "${image_dir}" "${imagerc_filename}" "${image_name}" "$2"
      exit $?
      ;;
  publish)
      source_imagerc "${image_dir}"  "${imagerc_filename}"
      production_image_tag="$(get_next_version)"
      docker_push "${AIT_DOCKER_IMAGE_NAME}" "${AIT_DOCKER_IMAGE_TAG}" "${production_image_tag}"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
