#!/bin/bash

set -e
RELEASER_VERSION="2.0.0"
RELEASER_FILE="ops/releaser-${RELEASER_VERSION}"

mkdir -p ops
if [[ ! -f $RELEASER_FILE ]];then
  wget --quiet -O $RELEASER_FILE https://github.com/kudulab/releaser/releases/download/2.0.0/releaser
fi
source $RELEASER_FILE

docker_ops=$(readlink -f ../../../../src/docker-ops)
source ${docker_ops}

image_dir1="./image1"
imagerc_filename1="imagerc1"
image_registry1="docker-registry1.ai-traders.com"
image_name1="docker-ops-private1"

image_dir2="./image2"
imagerc_filename2="imagerc2"
image_registry2="docker-registry2.ai-traders.com"
image_name2="docker-ops-private2"

set -u
command="$1"
case "${command}" in
  build)
      image_tag=$(git rev-parse HEAD)

      # build image1 and push to a test registry1
      docker_ops::docker_build "${image_dir1}" "${imagerc_filename1}" "${image_name1}" "${image_tag}" "${image_registry1}"
      docker_ops::push "${image_dir1}" "${imagerc_filename1}"

      # build image2 and push to a test registry1
      docker_ops::docker_build "${image_dir2}" "${imagerc_filename2}" "${image_name2}" "${image_tag}" "${image_registry1}"
      docker_ops::push "${image_dir2}" "${imagerc_filename2}"
      ;;
  test)
      docker_ops::ensure_pulled_image "${image_dir1}" "${imagerc_filename1}"
      echo "Testing image: ${KUDU_DOCKER_IMAGE_URL}"
      time bats --pretty "$(pwd)/test/integration/bats1"

      docker_ops::ensure_pulled_image "${image_dir2}" "${imagerc_filename2}"
      echo "Testing image: ${KUDU_DOCKER_IMAGE_URL}"
      time bats --pretty "$(pwd)/test/integration/bats2"
      ;;
  example)
      docker_ops::ensure_pulled_image "${image_dir1}" "${imagerc_filename1}"
      echo "Testing image: ${KUDU_DOCKER_IMAGE_URL}"
      docker run --rm ${KUDU_DOCKER_IMAGE_URL}

      docker_ops::ensure_pulled_image "${image_dir2}" "${imagerc_filename2}"
      echo "Testing image: ${KUDU_DOCKER_IMAGE_URL}"
      docker run --rm ${KUDU_DOCKER_IMAGE_URL}
      ;;
  set_version)
      if [[ -n "$2" ]]; then
        next_version="$2"
      else
        version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
        next_version=$(releaser::bump_patch_version "${version}")
      fi
      releaser::set_version_in_changelog "${changelog_file}" "${next_version}"
      exit $?
      ;;
  verify_version)
      releaser::verify_changelog_version
      exit $?
      ;;
  release)
      ./tasks verify_version
      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
      git tag "${version}" && git push origin "${version}"
      ;;
  publish)
      version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
      # push production image1 to image_registry1
      docker_ops::retag_push "${image_dir1}"  "${imagerc_filename1}" "${image_name1}" "${version}" "${image_registry1}"
      # push production image2 to image_registry2
      docker_ops::retag_push "${image_dir2}"  "${imagerc_filename2}" "${image_name2}" "${version}" "${image_registry2}"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
