format_version: 3
pipelines:
  docker-ops:
    group: platform
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - "**/*.md"
    stages:
      - test:
          clean_workspace: true
          jobs:
            itest:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ./tasks itest
      - release:
          clean_workspace: true
          jobs:
            code:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            code:
              secure_variables:
                VAULT_TOKEN: "AES:oo4qyY+eEf1piu8V4vy4hg==:nnH/4ulwI2JgjBtBiR+LGtB+PLLWVdtsCm+CIgjNHwj+qYXlvxWbN0+RS/tSi60N"
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
