#!/bin/bash

set -e

RELEASER_VERSION="2.0.0"
RELEASER_FILE=".ops/releaser-${RELEASER_VERSION}"

mkdir -p .ops
if [[ ! -f $RELEASER_FILE ]];then
  wget --quiet -O $RELEASER_FILE https://github.com/kudulab/releaser/releases/download/2.0.0/releaser
fi
source $RELEASER_FILE

command="$1"
case "${command}" in
  set_version)
      releaser::bump_changelog_version "$2" "$3"
      ;;
  verify_version)
      releaser::verify_version_for_release
      ;;
  itest)
      time bats ./test/integration/*.bats
      ;;
  test)
      ./tasks itest
      ;;
  release)
      releaser::verify_version_for_release
      releaser::git_tag_from_changelog
      ;;
  publish)
      # publish the just released version
      VERSION=$(releaser::get_last_git_tagged_version)
      releaser::prepare_github_release_bin
      $GHRELEASE_BIN release \
        --user kudulab \
        --repo docker-ops \
        --tag $VERSION \
        --name $VERSION \
        --pre-release

      $GHRELEASE_BIN upload \
        --user kudulab \
        --repo docker-ops \
        --tag $VERSION \
        --name "docker-ops" \
        --file src/docker-ops
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
