#!/bin/bash

if [[ ! -f ./releaser ]];then
  wget http://gogs.ai-traders.com/platform/releaser/raw/0.2.1/src/releaser
fi
source ./releaser
releaser_init

docker_ops=$(readlink -f ../../../../src/docker-ops)
source ${docker_ops}

command="$1"
case "${command}" in
  build)
      docker_build "${image_dir}" "${image_name}" "$2"
      exit $?
      ;;
  publish)
      source_imagerc "${image_dir}"
      production_image_tag="$(get_next_version)"
      docker_push "${AIT_DOCKER_IMAGE_NAME}" "${AIT_DOCKER_IMAGE_TAG}" "${production_image_tag}"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
